image: docker:git
services:
- docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com


build_alpine:
  script:
    - docker build -t registry.gitlab.com/gbraad/openstack-client:alpine ./alpine 
    - docker push registry.gitlab.com/gbraad/openstack-client:alpine
  only:
    - master

build_centos:
  script:
    - docker build -t registry.gitlab.com/gbraad/openstack-client:centos ./centos 
    - docker push registry.gitlab.com/gbraad/openstack-client:centos
  only:
    - master

build_ubuntu:
  script:
    - docker build -t registry.gitlab.com/gbraad/openstack-client:ubuntu ./ubuntu 
    - docker push registry.gitlab.com/gbraad/openstack-client:ubuntu
  only:
    - master
